### ISSUE TITLE
GLE Builds with empty folders

### ISSUE THREAD

**Issue by EterSky** [SuperHackio/GLEBuildTool#2]
Hey, so i've built GLE V3 with this tool, it builds the xml as it should but the folders it builds are empty and i don't think that's supposed to happen.

**Comment by SuperHackio** [comment]
What folders, exactly?

**Comment by EterSky** [comment]
The "GalaxyLevelEngine_V3_0_0_0_Region" folders

**Comment by SuperHackio** [comment]
Ah
The reason that this occurs is because you do not have the Resource files available for the build tool to copy over. There is nothing wrong with that, as the code correctly compiles without it.

There is no need to be worried about these empty folders. Hope that helps! 😄
