### ISSUE TITLE
errors with building GLE-V3 Beta i dont understand

### ISSUE THREAD

**Issue by amongusgamer63** [SuperHackio/GLEBuildTool#4]
**Describe the bug**
LOTS of errors when i try to build GLE-V3, they begin once it starts compiling the source files, i have no idea what they're referring to (maybe something folder path related?).

i dont know if this helps, but ill link the full log it gave me
[buildlog.txt](https://github.com/SuperHackio/GalaxyLevelEngine/files/12480858/buildlog.txt)
and a screenshot of my file layout
![Screenshot 2023-08-31 003409](https://github.com/SuperHackio/GalaxyLevelEngine/assets/128836721/8472cbff-e604-436a-8228-10c5a920e6e8)
![Screenshot 2023-08-31 004705](https://github.com/SuperHackio/GalaxyLevelEngine/assets/128836721/f77a6074-3fde-42c9-b51f-4fbd97501c89)

**Comment by SuperHackio** [comment]
It looks like the files in the "Tools" folder are incorrect.

Namely, the PowerPC compiler is likely the wrong file, wrong version, or wrong program entirely. (as it's saying that it does not recognize certain PowerPC based commands related to the Broadway Processor that's inside the Nintendo Wii)

**Comment by amongusgamer63** [comment]
yeah, i had the wrong compiler lol, it compiles fine now
